// Code generated by ent, DO NOT EDIT.

package honeypotevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the honeypotevent type in the database.
	Label = "honeypot_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldIsStream holds the string denoting the is_stream field in the database.
	FieldIsStream = "is_stream"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldBodyTruncated holds the string denoting the body_truncated field in the database.
	FieldBodyTruncated = "body_truncated"
	// FieldIntel holds the string denoting the intel field in the database.
	FieldIntel = "intel"
	// FieldInjectedPayload holds the string denoting the injected_payload field in the database.
	FieldInjectedPayload = "injected_payload"
	// FieldResponseMode holds the string denoting the response_mode field in the database.
	FieldResponseMode = "response_mode"
	// Table holds the table name of the honeypotevent in the database.
	Table = "honeypot_events"
)

// Columns holds all SQL columns for honeypotevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAPIKeyID,
	FieldSource,
	FieldMethod,
	FieldPath,
	FieldClientIP,
	FieldUserAgent,
	FieldModel,
	FieldIsStream,
	FieldHeaders,
	FieldBody,
	FieldBodyTruncated,
	FieldIntel,
	FieldInjectedPayload,
	FieldResponseMode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// DefaultPath holds the default value on creation for the "path" field.
	DefaultPath string
	// DefaultClientIP holds the default value on creation for the "client_ip" field.
	DefaultClientIP string
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultIsStream holds the default value on creation for the "is_stream" field.
	DefaultIsStream bool
	// DefaultBodyTruncated holds the default value on creation for the "body_truncated" field.
	DefaultBodyTruncated bool
	// DefaultResponseMode holds the default value on creation for the "response_mode" field.
	DefaultResponseMode string
	// ResponseModeValidator is a validator for the "response_mode" field. It is called by the builders before save.
	ResponseModeValidator func(string) error
)

// OrderOption defines the ordering options for the HoneypotEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByIsStream orders the results by the is_stream field.
func ByIsStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsStream, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByBodyTruncated orders the results by the body_truncated field.
func ByBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBodyTruncated, opts...).ToFunc()
}

// ByInjectedPayload orders the results by the injected_payload field.
func ByInjectedPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInjectedPayload, opts...).ToFunc()
}

// ByResponseMode orders the results by the response_mode field.
func ByResponseMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseMode, opts...).ToFunc()
}
