// Code generated by ent, DO NOT EDIT.

package honeypotevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldSource, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldPath, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldUserAgent, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldModel, v))
}

// IsStream applies equality check predicate on the "is_stream" field. It's identical to IsStreamEQ.
func IsStream(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldIsStream, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldBody, v))
}

// BodyTruncated applies equality check predicate on the "body_truncated" field. It's identical to BodyTruncatedEQ.
func BodyTruncated(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldBodyTruncated, v))
}

// InjectedPayload applies equality check predicate on the "injected_payload" field. It's identical to InjectedPayloadEQ.
func InjectedPayload(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldInjectedPayload, v))
}

// ResponseMode applies equality check predicate on the "response_mode" field. It's identical to ResponseModeEQ.
func ResponseMode(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldResponseMode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldAPIKeyID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldSource, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldPath, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldUserAgent, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldModel, v))
}

// IsStreamEQ applies the EQ predicate on the "is_stream" field.
func IsStreamEQ(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldIsStream, v))
}

// IsStreamNEQ applies the NEQ predicate on the "is_stream" field.
func IsStreamNEQ(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldIsStream, v))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotNull(FieldHeaders))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldBody, v))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotNull(FieldBody))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldBody, v))
}

// BodyTruncatedEQ applies the EQ predicate on the "body_truncated" field.
func BodyTruncatedEQ(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldBodyTruncated, v))
}

// BodyTruncatedNEQ applies the NEQ predicate on the "body_truncated" field.
func BodyTruncatedNEQ(v bool) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldBodyTruncated, v))
}

// IntelIsNil applies the IsNil predicate on the "intel" field.
func IntelIsNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIsNull(FieldIntel))
}

// IntelNotNil applies the NotNil predicate on the "intel" field.
func IntelNotNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotNull(FieldIntel))
}

// InjectedPayloadEQ applies the EQ predicate on the "injected_payload" field.
func InjectedPayloadEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldInjectedPayload, v))
}

// InjectedPayloadNEQ applies the NEQ predicate on the "injected_payload" field.
func InjectedPayloadNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldInjectedPayload, v))
}

// InjectedPayloadIn applies the In predicate on the "injected_payload" field.
func InjectedPayloadIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldInjectedPayload, vs...))
}

// InjectedPayloadNotIn applies the NotIn predicate on the "injected_payload" field.
func InjectedPayloadNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldInjectedPayload, vs...))
}

// InjectedPayloadGT applies the GT predicate on the "injected_payload" field.
func InjectedPayloadGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldInjectedPayload, v))
}

// InjectedPayloadGTE applies the GTE predicate on the "injected_payload" field.
func InjectedPayloadGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldInjectedPayload, v))
}

// InjectedPayloadLT applies the LT predicate on the "injected_payload" field.
func InjectedPayloadLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldInjectedPayload, v))
}

// InjectedPayloadLTE applies the LTE predicate on the "injected_payload" field.
func InjectedPayloadLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldInjectedPayload, v))
}

// InjectedPayloadContains applies the Contains predicate on the "injected_payload" field.
func InjectedPayloadContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldInjectedPayload, v))
}

// InjectedPayloadHasPrefix applies the HasPrefix predicate on the "injected_payload" field.
func InjectedPayloadHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldInjectedPayload, v))
}

// InjectedPayloadHasSuffix applies the HasSuffix predicate on the "injected_payload" field.
func InjectedPayloadHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldInjectedPayload, v))
}

// InjectedPayloadIsNil applies the IsNil predicate on the "injected_payload" field.
func InjectedPayloadIsNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIsNull(FieldInjectedPayload))
}

// InjectedPayloadNotNil applies the NotNil predicate on the "injected_payload" field.
func InjectedPayloadNotNil() predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotNull(FieldInjectedPayload))
}

// InjectedPayloadEqualFold applies the EqualFold predicate on the "injected_payload" field.
func InjectedPayloadEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldInjectedPayload, v))
}

// InjectedPayloadContainsFold applies the ContainsFold predicate on the "injected_payload" field.
func InjectedPayloadContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldInjectedPayload, v))
}

// ResponseModeEQ applies the EQ predicate on the "response_mode" field.
func ResponseModeEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEQ(FieldResponseMode, v))
}

// ResponseModeNEQ applies the NEQ predicate on the "response_mode" field.
func ResponseModeNEQ(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNEQ(FieldResponseMode, v))
}

// ResponseModeIn applies the In predicate on the "response_mode" field.
func ResponseModeIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldIn(FieldResponseMode, vs...))
}

// ResponseModeNotIn applies the NotIn predicate on the "response_mode" field.
func ResponseModeNotIn(vs ...string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldNotIn(FieldResponseMode, vs...))
}

// ResponseModeGT applies the GT predicate on the "response_mode" field.
func ResponseModeGT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGT(FieldResponseMode, v))
}

// ResponseModeGTE applies the GTE predicate on the "response_mode" field.
func ResponseModeGTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldGTE(FieldResponseMode, v))
}

// ResponseModeLT applies the LT predicate on the "response_mode" field.
func ResponseModeLT(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLT(FieldResponseMode, v))
}

// ResponseModeLTE applies the LTE predicate on the "response_mode" field.
func ResponseModeLTE(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldLTE(FieldResponseMode, v))
}

// ResponseModeContains applies the Contains predicate on the "response_mode" field.
func ResponseModeContains(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContains(FieldResponseMode, v))
}

// ResponseModeHasPrefix applies the HasPrefix predicate on the "response_mode" field.
func ResponseModeHasPrefix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasPrefix(FieldResponseMode, v))
}

// ResponseModeHasSuffix applies the HasSuffix predicate on the "response_mode" field.
func ResponseModeHasSuffix(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldHasSuffix(FieldResponseMode, v))
}

// ResponseModeEqualFold applies the EqualFold predicate on the "response_mode" field.
func ResponseModeEqualFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldEqualFold(FieldResponseMode, v))
}

// ResponseModeContainsFold applies the ContainsFold predicate on the "response_mode" field.
func ResponseModeContainsFold(v string) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.FieldContainsFold(FieldResponseMode, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HoneypotEvent) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HoneypotEvent) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HoneypotEvent) predicate.HoneypotEvent {
	return predicate.HoneypotEvent(sql.NotPredicates(p))
}
