// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/honeypotevent"
)

// HoneypotEvent is the model entity for the HoneypotEvent schema.
type HoneypotEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// IsStream holds the value of the "is_stream" field.
	IsStream bool `json:"is_stream,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers map[string]interface{} `json:"headers,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// BodyTruncated holds the value of the "body_truncated" field.
	BodyTruncated bool `json:"body_truncated,omitempty"`
	// Intel holds the value of the "intel" field.
	Intel map[string]interface{} `json:"intel,omitempty"`
	// InjectedPayload holds the value of the "injected_payload" field.
	InjectedPayload string `json:"injected_payload,omitempty"`
	// ResponseMode holds the value of the "response_mode" field.
	ResponseMode string `json:"response_mode,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HoneypotEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case honeypotevent.FieldHeaders, honeypotevent.FieldIntel:
			values[i] = new([]byte)
		case honeypotevent.FieldIsStream, honeypotevent.FieldBodyTruncated:
			values[i] = new(sql.NullBool)
		case honeypotevent.FieldID, honeypotevent.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case honeypotevent.FieldSource, honeypotevent.FieldMethod, honeypotevent.FieldPath, honeypotevent.FieldClientIP, honeypotevent.FieldUserAgent, honeypotevent.FieldModel, honeypotevent.FieldBody, honeypotevent.FieldInjectedPayload, honeypotevent.FieldResponseMode:
			values[i] = new(sql.NullString)
		case honeypotevent.FieldCreatedAt, honeypotevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HoneypotEvent fields.
func (_m *HoneypotEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case honeypotevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case honeypotevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case honeypotevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case honeypotevent.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case honeypotevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case honeypotevent.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case honeypotevent.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case honeypotevent.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case honeypotevent.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case honeypotevent.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case honeypotevent.FieldIsStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_stream", values[i])
			} else if value.Valid {
				_m.IsStream = value.Bool
			}
		case honeypotevent.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case honeypotevent.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case honeypotevent.FieldBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field body_truncated", values[i])
			} else if value.Valid {
				_m.BodyTruncated = value.Bool
			}
		case honeypotevent.FieldIntel:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field intel", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Intel); err != nil {
					return fmt.Errorf("unmarshal field intel: %w", err)
				}
			}
		case honeypotevent.FieldInjectedPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field injected_payload", values[i])
			} else if value.Valid {
				_m.InjectedPayload = value.String
			}
		case honeypotevent.FieldResponseMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_mode", values[i])
			} else if value.Valid {
				_m.ResponseMode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HoneypotEvent.
// This includes values selected through modifiers, order, etc.
func (_m *HoneypotEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HoneypotEvent.
// Note that you need to call HoneypotEvent.Unwrap() before calling this method if this HoneypotEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HoneypotEvent) Update() *HoneypotEventUpdateOne {
	return NewHoneypotEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HoneypotEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HoneypotEvent) Unwrap() *HoneypotEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HoneypotEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HoneypotEvent) String() string {
	var builder strings.Builder
	builder.WriteString("HoneypotEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("is_stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsStream))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.BodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("intel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Intel))
	builder.WriteString(", ")
	builder.WriteString("injected_payload=")
	builder.WriteString(_m.InjectedPayload)
	builder.WriteString(", ")
	builder.WriteString("response_mode=")
	builder.WriteString(_m.ResponseMode)
	builder.WriteByte(')')
	return builder.String()
}

// HoneypotEvents is a parsable slice of HoneypotEvent.
type HoneypotEvents []*HoneypotEvent
