// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/honeypotevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// HoneypotEventUpdate is the builder for updating HoneypotEvent entities.
type HoneypotEventUpdate struct {
	config
	hooks    []Hook
	mutation *HoneypotEventMutation
}

// Where appends a list predicates to the HoneypotEventUpdate builder.
func (_u *HoneypotEventUpdate) Where(ps ...predicate.HoneypotEvent) *HoneypotEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HoneypotEventUpdate) SetUpdatedAt(v time.Time) *HoneypotEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *HoneypotEventUpdate) SetAPIKeyID(v int64) *HoneypotEventUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableAPIKeyID(v *int64) *HoneypotEventUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *HoneypotEventUpdate) AddAPIKeyID(v int64) *HoneypotEventUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *HoneypotEventUpdate) SetSource(v string) *HoneypotEventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableSource(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *HoneypotEventUpdate) SetMethod(v string) *HoneypotEventUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableMethod(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *HoneypotEventUpdate) SetPath(v string) *HoneypotEventUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillablePath(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *HoneypotEventUpdate) SetClientIP(v string) *HoneypotEventUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableClientIP(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *HoneypotEventUpdate) SetUserAgent(v string) *HoneypotEventUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableUserAgent(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *HoneypotEventUpdate) ClearUserAgent() *HoneypotEventUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetModel sets the "model" field.
func (_u *HoneypotEventUpdate) SetModel(v string) *HoneypotEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableModel(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetIsStream sets the "is_stream" field.
func (_u *HoneypotEventUpdate) SetIsStream(v bool) *HoneypotEventUpdate {
	_u.mutation.SetIsStream(v)
	return _u
}

// SetNillableIsStream sets the "is_stream" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableIsStream(v *bool) *HoneypotEventUpdate {
	if v != nil {
		_u.SetIsStream(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *HoneypotEventUpdate) SetHeaders(v map[string]interface{}) *HoneypotEventUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *HoneypotEventUpdate) ClearHeaders() *HoneypotEventUpdate {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *HoneypotEventUpdate) SetBody(v string) *HoneypotEventUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableBody(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *HoneypotEventUpdate) ClearBody() *HoneypotEventUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetBodyTruncated sets the "body_truncated" field.
func (_u *HoneypotEventUpdate) SetBodyTruncated(v bool) *HoneypotEventUpdate {
	_u.mutation.SetBodyTruncated(v)
	return _u
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableBodyTruncated(v *bool) *HoneypotEventUpdate {
	if v != nil {
		_u.SetBodyTruncated(*v)
	}
	return _u
}

// SetIntel sets the "intel" field.
func (_u *HoneypotEventUpdate) SetIntel(v map[string]interface{}) *HoneypotEventUpdate {
	_u.mutation.SetIntel(v)
	return _u
}

// ClearIntel clears the value of the "intel" field.
func (_u *HoneypotEventUpdate) ClearIntel() *HoneypotEventUpdate {
	_u.mutation.ClearIntel()
	return _u
}

// SetInjectedPayload sets the "injected_payload" field.
func (_u *HoneypotEventUpdate) SetInjectedPayload(v string) *HoneypotEventUpdate {
	_u.mutation.SetInjectedPayload(v)
	return _u
}

// SetNillableInjectedPayload sets the "injected_payload" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableInjectedPayload(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetInjectedPayload(*v)
	}
	return _u
}

// ClearInjectedPayload clears the value of the "injected_payload" field.
func (_u *HoneypotEventUpdate) ClearInjectedPayload() *HoneypotEventUpdate {
	_u.mutation.ClearInjectedPayload()
	return _u
}

// SetResponseMode sets the "response_mode" field.
func (_u *HoneypotEventUpdate) SetResponseMode(v string) *HoneypotEventUpdate {
	_u.mutation.SetResponseMode(v)
	return _u
}

// SetNillableResponseMode sets the "response_mode" field if the given value is not nil.
func (_u *HoneypotEventUpdate) SetNillableResponseMode(v *string) *HoneypotEventUpdate {
	if v != nil {
		_u.SetResponseMode(*v)
	}
	return _u
}

// Mutation returns the HoneypotEventMutation object of the builder.
func (_u *HoneypotEventUpdate) Mutation() *HoneypotEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HoneypotEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HoneypotEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HoneypotEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HoneypotEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HoneypotEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := honeypotevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HoneypotEventUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := honeypotevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := honeypotevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := honeypotevent.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMode(); ok {
		if err := honeypotevent.ResponseModeValidator(v); err != nil {
			return &ValidationError{Name: "response_mode", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.response_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *HoneypotEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(honeypotevent.Table, honeypotevent.Columns, sqlgraph.NewFieldSpec(honeypotevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(honeypotevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(honeypotevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(honeypotevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(honeypotevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(honeypotevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(honeypotevent.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(honeypotevent.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(honeypotevent.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(honeypotevent.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(honeypotevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsStream(); ok {
		_spec.SetField(honeypotevent.FieldIsStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(honeypotevent.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(honeypotevent.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(honeypotevent.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(honeypotevent.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.BodyTruncated(); ok {
		_spec.SetField(honeypotevent.FieldBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Intel(); ok {
		_spec.SetField(honeypotevent.FieldIntel, field.TypeJSON, value)
	}
	if _u.mutation.IntelCleared() {
		_spec.ClearField(honeypotevent.FieldIntel, field.TypeJSON)
	}
	if value, ok := _u.mutation.InjectedPayload(); ok {
		_spec.SetField(honeypotevent.FieldInjectedPayload, field.TypeString, value)
	}
	if _u.mutation.InjectedPayloadCleared() {
		_spec.ClearField(honeypotevent.FieldInjectedPayload, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseMode(); ok {
		_spec.SetField(honeypotevent.FieldResponseMode, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{honeypotevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HoneypotEventUpdateOne is the builder for updating a single HoneypotEvent entity.
type HoneypotEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HoneypotEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HoneypotEventUpdateOne) SetUpdatedAt(v time.Time) *HoneypotEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *HoneypotEventUpdateOne) SetAPIKeyID(v int64) *HoneypotEventUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableAPIKeyID(v *int64) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *HoneypotEventUpdateOne) AddAPIKeyID(v int64) *HoneypotEventUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *HoneypotEventUpdateOne) SetSource(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableSource(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *HoneypotEventUpdateOne) SetMethod(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableMethod(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *HoneypotEventUpdateOne) SetPath(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillablePath(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *HoneypotEventUpdateOne) SetClientIP(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableClientIP(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *HoneypotEventUpdateOne) SetUserAgent(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableUserAgent(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *HoneypotEventUpdateOne) ClearUserAgent() *HoneypotEventUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetModel sets the "model" field.
func (_u *HoneypotEventUpdateOne) SetModel(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableModel(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetIsStream sets the "is_stream" field.
func (_u *HoneypotEventUpdateOne) SetIsStream(v bool) *HoneypotEventUpdateOne {
	_u.mutation.SetIsStream(v)
	return _u
}

// SetNillableIsStream sets the "is_stream" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableIsStream(v *bool) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetIsStream(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *HoneypotEventUpdateOne) SetHeaders(v map[string]interface{}) *HoneypotEventUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *HoneypotEventUpdateOne) ClearHeaders() *HoneypotEventUpdateOne {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *HoneypotEventUpdateOne) SetBody(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableBody(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *HoneypotEventUpdateOne) ClearBody() *HoneypotEventUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetBodyTruncated sets the "body_truncated" field.
func (_u *HoneypotEventUpdateOne) SetBodyTruncated(v bool) *HoneypotEventUpdateOne {
	_u.mutation.SetBodyTruncated(v)
	return _u
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableBodyTruncated(v *bool) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetBodyTruncated(*v)
	}
	return _u
}

// SetIntel sets the "intel" field.
func (_u *HoneypotEventUpdateOne) SetIntel(v map[string]interface{}) *HoneypotEventUpdateOne {
	_u.mutation.SetIntel(v)
	return _u
}

// ClearIntel clears the value of the "intel" field.
func (_u *HoneypotEventUpdateOne) ClearIntel() *HoneypotEventUpdateOne {
	_u.mutation.ClearIntel()
	return _u
}

// SetInjectedPayload sets the "injected_payload" field.
func (_u *HoneypotEventUpdateOne) SetInjectedPayload(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetInjectedPayload(v)
	return _u
}

// SetNillableInjectedPayload sets the "injected_payload" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableInjectedPayload(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetInjectedPayload(*v)
	}
	return _u
}

// ClearInjectedPayload clears the value of the "injected_payload" field.
func (_u *HoneypotEventUpdateOne) ClearInjectedPayload() *HoneypotEventUpdateOne {
	_u.mutation.ClearInjectedPayload()
	return _u
}

// SetResponseMode sets the "response_mode" field.
func (_u *HoneypotEventUpdateOne) SetResponseMode(v string) *HoneypotEventUpdateOne {
	_u.mutation.SetResponseMode(v)
	return _u
}

// SetNillableResponseMode sets the "response_mode" field if the given value is not nil.
func (_u *HoneypotEventUpdateOne) SetNillableResponseMode(v *string) *HoneypotEventUpdateOne {
	if v != nil {
		_u.SetResponseMode(*v)
	}
	return _u
}

// Mutation returns the HoneypotEventMutation object of the builder.
func (_u *HoneypotEventUpdateOne) Mutation() *HoneypotEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the HoneypotEventUpdate builder.
func (_u *HoneypotEventUpdateOne) Where(ps ...predicate.HoneypotEvent) *HoneypotEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HoneypotEventUpdateOne) Select(field string, fields ...string) *HoneypotEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HoneypotEvent entity.
func (_u *HoneypotEventUpdateOne) Save(ctx context.Context) (*HoneypotEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HoneypotEventUpdateOne) SaveX(ctx context.Context) *HoneypotEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HoneypotEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HoneypotEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HoneypotEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := honeypotevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HoneypotEventUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := honeypotevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := honeypotevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := honeypotevent.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMode(); ok {
		if err := honeypotevent.ResponseModeValidator(v); err != nil {
			return &ValidationError{Name: "response_mode", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.response_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *HoneypotEventUpdateOne) sqlSave(ctx context.Context) (_node *HoneypotEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(honeypotevent.Table, honeypotevent.Columns, sqlgraph.NewFieldSpec(honeypotevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HoneypotEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, honeypotevent.FieldID)
		for _, f := range fields {
			if !honeypotevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != honeypotevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(honeypotevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(honeypotevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(honeypotevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(honeypotevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(honeypotevent.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(honeypotevent.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(honeypotevent.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(honeypotevent.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(honeypotevent.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(honeypotevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsStream(); ok {
		_spec.SetField(honeypotevent.FieldIsStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(honeypotevent.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(honeypotevent.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(honeypotevent.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(honeypotevent.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.BodyTruncated(); ok {
		_spec.SetField(honeypotevent.FieldBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Intel(); ok {
		_spec.SetField(honeypotevent.FieldIntel, field.TypeJSON, value)
	}
	if _u.mutation.IntelCleared() {
		_spec.ClearField(honeypotevent.FieldIntel, field.TypeJSON)
	}
	if value, ok := _u.mutation.InjectedPayload(); ok {
		_spec.SetField(honeypotevent.FieldInjectedPayload, field.TypeString, value)
	}
	if _u.mutation.InjectedPayloadCleared() {
		_spec.ClearField(honeypotevent.FieldInjectedPayload, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseMode(); ok {
		_spec.SetField(honeypotevent.FieldResponseMode, field.TypeString, value)
	}
	_node = &HoneypotEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{honeypotevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
