// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/honeypotevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// HoneypotEventDelete is the builder for deleting a HoneypotEvent entity.
type HoneypotEventDelete struct {
	config
	hooks    []Hook
	mutation *HoneypotEventMutation
}

// Where appends a list predicates to the HoneypotEventDelete builder.
func (_d *HoneypotEventDelete) Where(ps ...predicate.HoneypotEvent) *HoneypotEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HoneypotEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HoneypotEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HoneypotEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(honeypotevent.Table, sqlgraph.NewFieldSpec(honeypotevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HoneypotEventDeleteOne is the builder for deleting a single HoneypotEvent entity.
type HoneypotEventDeleteOne struct {
	_d *HoneypotEventDelete
}

// Where appends a list predicates to the HoneypotEventDelete builder.
func (_d *HoneypotEventDeleteOne) Where(ps ...predicate.HoneypotEvent) *HoneypotEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HoneypotEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{honeypotevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HoneypotEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
