// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/honeypotevent"
)

// HoneypotEventCreate is the builder for creating a HoneypotEvent entity.
type HoneypotEventCreate struct {
	config
	mutation *HoneypotEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HoneypotEventCreate) SetCreatedAt(v time.Time) *HoneypotEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableCreatedAt(v *time.Time) *HoneypotEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HoneypotEventCreate) SetUpdatedAt(v time.Time) *HoneypotEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableUpdatedAt(v *time.Time) *HoneypotEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *HoneypotEventCreate) SetAPIKeyID(v int64) *HoneypotEventCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *HoneypotEventCreate) SetSource(v string) *HoneypotEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableSource(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *HoneypotEventCreate) SetMethod(v string) *HoneypotEventCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableMethod(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *HoneypotEventCreate) SetPath(v string) *HoneypotEventCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillablePath(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *HoneypotEventCreate) SetClientIP(v string) *HoneypotEventCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableClientIP(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *HoneypotEventCreate) SetUserAgent(v string) *HoneypotEventCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableUserAgent(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *HoneypotEventCreate) SetModel(v string) *HoneypotEventCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableModel(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetIsStream sets the "is_stream" field.
func (_c *HoneypotEventCreate) SetIsStream(v bool) *HoneypotEventCreate {
	_c.mutation.SetIsStream(v)
	return _c
}

// SetNillableIsStream sets the "is_stream" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableIsStream(v *bool) *HoneypotEventCreate {
	if v != nil {
		_c.SetIsStream(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *HoneypotEventCreate) SetHeaders(v map[string]interface{}) *HoneypotEventCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *HoneypotEventCreate) SetBody(v string) *HoneypotEventCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableBody(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetBodyTruncated sets the "body_truncated" field.
func (_c *HoneypotEventCreate) SetBodyTruncated(v bool) *HoneypotEventCreate {
	_c.mutation.SetBodyTruncated(v)
	return _c
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableBodyTruncated(v *bool) *HoneypotEventCreate {
	if v != nil {
		_c.SetBodyTruncated(*v)
	}
	return _c
}

// SetIntel sets the "intel" field.
func (_c *HoneypotEventCreate) SetIntel(v map[string]interface{}) *HoneypotEventCreate {
	_c.mutation.SetIntel(v)
	return _c
}

// SetInjectedPayload sets the "injected_payload" field.
func (_c *HoneypotEventCreate) SetInjectedPayload(v string) *HoneypotEventCreate {
	_c.mutation.SetInjectedPayload(v)
	return _c
}

// SetNillableInjectedPayload sets the "injected_payload" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableInjectedPayload(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetInjectedPayload(*v)
	}
	return _c
}

// SetResponseText sets the "response_text" field.
func (_c *HoneypotEventCreate) SetResponseText(v string) *HoneypotEventCreate {
	_c.mutation.SetResponseText(v)
	return _c
}

// SetNillableResponseText sets the "response_text" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableResponseText(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetResponseText(*v)
	}
	return _c
}

// SetResponseMode sets the "response_mode" field.
func (_c *HoneypotEventCreate) SetResponseMode(v string) *HoneypotEventCreate {
	_c.mutation.SetResponseMode(v)
	return _c
}

// SetNillableResponseMode sets the "response_mode" field if the given value is not nil.
func (_c *HoneypotEventCreate) SetNillableResponseMode(v *string) *HoneypotEventCreate {
	if v != nil {
		_c.SetResponseMode(*v)
	}
	return _c
}

// Mutation returns the HoneypotEventMutation object of the builder.
func (_c *HoneypotEventCreate) Mutation() *HoneypotEventMutation {
	return _c.mutation
}

// Save creates the HoneypotEvent in the database.
func (_c *HoneypotEventCreate) Save(ctx context.Context) (*HoneypotEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HoneypotEventCreate) SaveX(ctx context.Context) *HoneypotEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HoneypotEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HoneypotEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HoneypotEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := honeypotevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := honeypotevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := honeypotevent.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := honeypotevent.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := honeypotevent.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.ClientIP(); !ok {
		v := honeypotevent.DefaultClientIP
		_c.mutation.SetClientIP(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := honeypotevent.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.IsStream(); !ok {
		v := honeypotevent.DefaultIsStream
		_c.mutation.SetIsStream(v)
	}
	if _, ok := _c.mutation.BodyTruncated(); !ok {
		v := honeypotevent.DefaultBodyTruncated
		_c.mutation.SetBodyTruncated(v)
	}
	if _, ok := _c.mutation.ResponseMode(); !ok {
		v := honeypotevent.DefaultResponseMode
		_c.mutation.SetResponseMode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HoneypotEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HoneypotEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HoneypotEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "HoneypotEvent.api_key_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "HoneypotEvent.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := honeypotevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "HoneypotEvent.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := honeypotevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "HoneypotEvent.path"`)}
	}
	if _, ok := _c.mutation.ClientIP(); !ok {
		return &ValidationError{Name: "client_ip", err: errors.New(`ent: missing required field "HoneypotEvent.client_ip"`)}
	}
	if v, ok := _c.mutation.ClientIP(); ok {
		if err := honeypotevent.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.client_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "HoneypotEvent.model"`)}
	}
	if _, ok := _c.mutation.IsStream(); !ok {
		return &ValidationError{Name: "is_stream", err: errors.New(`ent: missing required field "HoneypotEvent.is_stream"`)}
	}
	if _, ok := _c.mutation.BodyTruncated(); !ok {
		return &ValidationError{Name: "body_truncated", err: errors.New(`ent: missing required field "HoneypotEvent.body_truncated"`)}
	}
	if _, ok := _c.mutation.ResponseMode(); !ok {
		return &ValidationError{Name: "response_mode", err: errors.New(`ent: missing required field "HoneypotEvent.response_mode"`)}
	}
	if v, ok := _c.mutation.ResponseMode(); ok {
		if err := honeypotevent.ResponseModeValidator(v); err != nil {
			return &ValidationError{Name: "response_mode", err: fmt.Errorf(`ent: validator failed for field "HoneypotEvent.response_mode": %w`, err)}
		}
	}
	return nil
}

func (_c *HoneypotEventCreate) sqlSave(ctx context.Context) (*HoneypotEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HoneypotEventCreate) createSpec() (*HoneypotEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &HoneypotEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(honeypotevent.Table, sqlgraph.NewFieldSpec(honeypotevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(honeypotevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(honeypotevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(honeypotevent.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(honeypotevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(honeypotevent.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(honeypotevent.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(honeypotevent.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(honeypotevent.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(honeypotevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.IsStream(); ok {
		_spec.SetField(honeypotevent.FieldIsStream, field.TypeBool, value)
		_node.IsStream = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(honeypotevent.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(honeypotevent.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.BodyTruncated(); ok {
		_spec.SetField(honeypotevent.FieldBodyTruncated, field.TypeBool, value)
		_node.BodyTruncated = value
	}
	if value, ok := _c.mutation.Intel(); ok {
		_spec.SetField(honeypotevent.FieldIntel, field.TypeJSON, value)
		_node.Intel = value
	}
	if value, ok := _c.mutation.InjectedPayload(); ok {
		_spec.SetField(honeypotevent.FieldInjectedPayload, field.TypeString, value)
		_node.InjectedPayload = value
	}
	if value, ok := _c.mutation.ResponseText(); ok {
		_spec.SetField(honeypotevent.FieldResponseText, field.TypeString, value)
		_node.ResponseText = value
	}
	if value, ok := _c.mutation.ResponseMode(); ok {
		_spec.SetField(honeypotevent.FieldResponseMode, field.TypeString, value)
		_node.ResponseMode = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HoneypotEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HoneypotEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HoneypotEventCreate) OnConflict(opts ...sql.ConflictOption) *HoneypotEventUpsertOne {
	_c.conflict = opts
	return &HoneypotEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HoneypotEventCreate) OnConflictColumns(columns ...string) *HoneypotEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HoneypotEventUpsertOne{
		create: _c,
	}
}

type (
	// HoneypotEventUpsertOne is the builder for "upsert"-ing
	//  one HoneypotEvent node.
	HoneypotEventUpsertOne struct {
		create *HoneypotEventCreate
	}

	// HoneypotEventUpsert is the "OnConflict" setter.
	HoneypotEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HoneypotEventUpsert) SetUpdatedAt(v time.Time) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateUpdatedAt() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *HoneypotEventUpsert) SetAPIKeyID(v int64) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateAPIKeyID() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *HoneypotEventUpsert) AddAPIKeyID(v int64) *HoneypotEventUpsert {
	u.Add(honeypotevent.FieldAPIKeyID, v)
	return u
}

// SetSource sets the "source" field.
func (u *HoneypotEventUpsert) SetSource(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateSource() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldSource)
	return u
}

// SetMethod sets the "method" field.
func (u *HoneypotEventUpsert) SetMethod(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateMethod() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldMethod)
	return u
}

// SetPath sets the "path" field.
func (u *HoneypotEventUpsert) SetPath(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdatePath() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldPath)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *HoneypotEventUpsert) SetClientIP(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateClientIP() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldClientIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *HoneypotEventUpsert) SetUserAgent(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateUserAgent() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *HoneypotEventUpsert) ClearUserAgent() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldUserAgent)
	return u
}

// SetModel sets the "model" field.
func (u *HoneypotEventUpsert) SetModel(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateModel() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldModel)
	return u
}

// SetIsStream sets the "is_stream" field.
func (u *HoneypotEventUpsert) SetIsStream(v bool) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldIsStream, v)
	return u
}

// UpdateIsStream sets the "is_stream" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateIsStream() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldIsStream)
	return u
}

// SetHeaders sets the "headers" field.
func (u *HoneypotEventUpsert) SetHeaders(v map[string]interface{}) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldHeaders, v)
	return u
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateHeaders() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldHeaders)
	return u
}

// ClearHeaders clears the value of the "headers" field.
func (u *HoneypotEventUpsert) ClearHeaders() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldHeaders)
	return u
}

// SetBody sets the "body" field.
func (u *HoneypotEventUpsert) SetBody(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateBody() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldBody)
	return u
}

// ClearBody clears the value of the "body" field.
func (u *HoneypotEventUpsert) ClearBody() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldBody)
	return u
}

// SetBodyTruncated sets the "body_truncated" field.
func (u *HoneypotEventUpsert) SetBodyTruncated(v bool) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldBodyTruncated, v)
	return u
}

// UpdateBodyTruncated sets the "body_truncated" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateBodyTruncated() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldBodyTruncated)
	return u
}

// SetIntel sets the "intel" field.
func (u *HoneypotEventUpsert) SetIntel(v map[string]interface{}) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldIntel, v)
	return u
}

// UpdateIntel sets the "intel" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateIntel() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldIntel)
	return u
}

// ClearIntel clears the value of the "intel" field.
func (u *HoneypotEventUpsert) ClearIntel() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldIntel)
	return u
}

// SetInjectedPayload sets the "injected_payload" field.
func (u *HoneypotEventUpsert) SetInjectedPayload(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldInjectedPayload, v)
	return u
}

// UpdateInjectedPayload sets the "injected_payload" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateInjectedPayload() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldInjectedPayload)
	return u
}

// ClearInjectedPayload clears the value of the "injected_payload" field.
func (u *HoneypotEventUpsert) ClearInjectedPayload() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldInjectedPayload)
	return u
}

// SetResponseText sets the "response_text" field.
func (u *HoneypotEventUpsert) SetResponseText(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldResponseText, v)
	return u
}

// UpdateResponseText sets the "response_text" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateResponseText() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldResponseText)
	return u
}

// ClearResponseText clears the value of the "response_text" field.
func (u *HoneypotEventUpsert) ClearResponseText() *HoneypotEventUpsert {
	u.SetNull(honeypotevent.FieldResponseText)
	return u
}

// SetResponseMode sets the "response_mode" field.
func (u *HoneypotEventUpsert) SetResponseMode(v string) *HoneypotEventUpsert {
	u.Set(honeypotevent.FieldResponseMode, v)
	return u
}

// UpdateResponseMode sets the "response_mode" field to the value that was provided on create.
func (u *HoneypotEventUpsert) UpdateResponseMode() *HoneypotEventUpsert {
	u.SetExcluded(honeypotevent.FieldResponseMode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HoneypotEventUpsertOne) UpdateNewValues() *HoneypotEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(honeypotevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HoneypotEventUpsertOne) Ignore() *HoneypotEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HoneypotEventUpsertOne) DoNothing() *HoneypotEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HoneypotEventCreate.OnConflict
// documentation for more info.
func (u *HoneypotEventUpsertOne) Update(set func(*HoneypotEventUpsert)) *HoneypotEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HoneypotEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HoneypotEventUpsertOne) SetUpdatedAt(v time.Time) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateUpdatedAt() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *HoneypotEventUpsertOne) SetAPIKeyID(v int64) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *HoneypotEventUpsertOne) AddAPIKeyID(v int64) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateAPIKeyID() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetSource sets the "source" field.
func (u *HoneypotEventUpsertOne) SetSource(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateSource() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateSource()
	})
}

// SetMethod sets the "method" field.
func (u *HoneypotEventUpsertOne) SetMethod(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateMethod() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateMethod()
	})
}

// SetPath sets the "path" field.
func (u *HoneypotEventUpsertOne) SetPath(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdatePath() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdatePath()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *HoneypotEventUpsertOne) SetClientIP(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateClientIP() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *HoneypotEventUpsertOne) SetUserAgent(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateUserAgent() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *HoneypotEventUpsertOne) ClearUserAgent() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearUserAgent()
	})
}

// SetModel sets the "model" field.
func (u *HoneypotEventUpsertOne) SetModel(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateModel() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateModel()
	})
}

// SetIsStream sets the "is_stream" field.
func (u *HoneypotEventUpsertOne) SetIsStream(v bool) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetIsStream(v)
	})
}

// UpdateIsStream sets the "is_stream" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateIsStream() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateIsStream()
	})
}

// SetHeaders sets the "headers" field.
func (u *HoneypotEventUpsertOne) SetHeaders(v map[string]interface{}) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateHeaders() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateHeaders()
	})
}

// ClearHeaders clears the value of the "headers" field.
func (u *HoneypotEventUpsertOne) ClearHeaders() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearHeaders()
	})
}

// SetBody sets the "body" field.
func (u *HoneypotEventUpsertOne) SetBody(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateBody() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateBody()
	})
}

// ClearBody clears the value of the "body" field.
func (u *HoneypotEventUpsertOne) ClearBody() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearBody()
	})
}

// SetBodyTruncated sets the "body_truncated" field.
func (u *HoneypotEventUpsertOne) SetBodyTruncated(v bool) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetBodyTruncated(v)
	})
}

// UpdateBodyTruncated sets the "body_truncated" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateBodyTruncated() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateBodyTruncated()
	})
}

// SetIntel sets the "intel" field.
func (u *HoneypotEventUpsertOne) SetIntel(v map[string]interface{}) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetIntel(v)
	})
}

// UpdateIntel sets the "intel" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateIntel() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateIntel()
	})
}

// ClearIntel clears the value of the "intel" field.
func (u *HoneypotEventUpsertOne) ClearIntel() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearIntel()
	})
}

// SetInjectedPayload sets the "injected_payload" field.
func (u *HoneypotEventUpsertOne) SetInjectedPayload(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetInjectedPayload(v)
	})
}

// UpdateInjectedPayload sets the "injected_payload" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateInjectedPayload() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateInjectedPayload()
	})
}

// ClearInjectedPayload clears the value of the "injected_payload" field.
func (u *HoneypotEventUpsertOne) ClearInjectedPayload() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearInjectedPayload()
	})
}

// SetResponseText sets the "response_text" field.
func (u *HoneypotEventUpsertOne) SetResponseText(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetResponseText(v)
	})
}

// UpdateResponseText sets the "response_text" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateResponseText() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateResponseText()
	})
}

// ClearResponseText clears the value of the "response_text" field.
func (u *HoneypotEventUpsertOne) ClearResponseText() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearResponseText()
	})
}

// SetResponseMode sets the "response_mode" field.
func (u *HoneypotEventUpsertOne) SetResponseMode(v string) *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetResponseMode(v)
	})
}

// UpdateResponseMode sets the "response_mode" field to the value that was provided on create.
func (u *HoneypotEventUpsertOne) UpdateResponseMode() *HoneypotEventUpsertOne {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateResponseMode()
	})
}

// Exec executes the query.
func (u *HoneypotEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HoneypotEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HoneypotEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HoneypotEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HoneypotEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HoneypotEventCreateBulk is the builder for creating many HoneypotEvent entities in bulk.
type HoneypotEventCreateBulk struct {
	config
	err      error
	builders []*HoneypotEventCreate
	conflict []sql.ConflictOption
}

// Save creates the HoneypotEvent entities in the database.
func (_c *HoneypotEventCreateBulk) Save(ctx context.Context) ([]*HoneypotEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HoneypotEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoneypotEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HoneypotEventCreateBulk) SaveX(ctx context.Context) []*HoneypotEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HoneypotEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HoneypotEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HoneypotEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HoneypotEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HoneypotEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *HoneypotEventUpsertBulk {
	_c.conflict = opts
	return &HoneypotEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HoneypotEventCreateBulk) OnConflictColumns(columns ...string) *HoneypotEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HoneypotEventUpsertBulk{
		create: _c,
	}
}

// HoneypotEventUpsertBulk is the builder for "upsert"-ing
// a bulk of HoneypotEvent nodes.
type HoneypotEventUpsertBulk struct {
	create *HoneypotEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HoneypotEventUpsertBulk) UpdateNewValues() *HoneypotEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(honeypotevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HoneypotEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HoneypotEventUpsertBulk) Ignore() *HoneypotEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HoneypotEventUpsertBulk) DoNothing() *HoneypotEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HoneypotEventCreateBulk.OnConflict
// documentation for more info.
func (u *HoneypotEventUpsertBulk) Update(set func(*HoneypotEventUpsert)) *HoneypotEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HoneypotEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HoneypotEventUpsertBulk) SetUpdatedAt(v time.Time) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateUpdatedAt() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *HoneypotEventUpsertBulk) SetAPIKeyID(v int64) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *HoneypotEventUpsertBulk) AddAPIKeyID(v int64) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateAPIKeyID() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetSource sets the "source" field.
func (u *HoneypotEventUpsertBulk) SetSource(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateSource() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateSource()
	})
}

// SetMethod sets the "method" field.
func (u *HoneypotEventUpsertBulk) SetMethod(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateMethod() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateMethod()
	})
}

// SetPath sets the "path" field.
func (u *HoneypotEventUpsertBulk) SetPath(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdatePath() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdatePath()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *HoneypotEventUpsertBulk) SetClientIP(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateClientIP() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *HoneypotEventUpsertBulk) SetUserAgent(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateUserAgent() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *HoneypotEventUpsertBulk) ClearUserAgent() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearUserAgent()
	})
}

// SetModel sets the "model" field.
func (u *HoneypotEventUpsertBulk) SetModel(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateModel() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateModel()
	})
}

// SetIsStream sets the "is_stream" field.
func (u *HoneypotEventUpsertBulk) SetIsStream(v bool) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetIsStream(v)
	})
}

// UpdateIsStream sets the "is_stream" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateIsStream() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateIsStream()
	})
}

// SetHeaders sets the "headers" field.
func (u *HoneypotEventUpsertBulk) SetHeaders(v map[string]interface{}) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateHeaders() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateHeaders()
	})
}

// ClearHeaders clears the value of the "headers" field.
func (u *HoneypotEventUpsertBulk) ClearHeaders() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearHeaders()
	})
}

// SetBody sets the "body" field.
func (u *HoneypotEventUpsertBulk) SetBody(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateBody() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateBody()
	})
}

// ClearBody clears the value of the "body" field.
func (u *HoneypotEventUpsertBulk) ClearBody() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearBody()
	})
}

// SetBodyTruncated sets the "body_truncated" field.
func (u *HoneypotEventUpsertBulk) SetBodyTruncated(v bool) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetBodyTruncated(v)
	})
}

// UpdateBodyTruncated sets the "body_truncated" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateBodyTruncated() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateBodyTruncated()
	})
}

// SetIntel sets the "intel" field.
func (u *HoneypotEventUpsertBulk) SetIntel(v map[string]interface{}) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetIntel(v)
	})
}

// UpdateIntel sets the "intel" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateIntel() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateIntel()
	})
}

// ClearIntel clears the value of the "intel" field.
func (u *HoneypotEventUpsertBulk) ClearIntel() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearIntel()
	})
}

// SetInjectedPayload sets the "injected_payload" field.
func (u *HoneypotEventUpsertBulk) SetInjectedPayload(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetInjectedPayload(v)
	})
}

// UpdateInjectedPayload sets the "injected_payload" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateInjectedPayload() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateInjectedPayload()
	})
}

// ClearInjectedPayload clears the value of the "injected_payload" field.
func (u *HoneypotEventUpsertBulk) ClearInjectedPayload() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearInjectedPayload()
	})
}

// SetResponseText sets the "response_text" field.
func (u *HoneypotEventUpsertBulk) SetResponseText(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetResponseText(v)
	})
}

// UpdateResponseText sets the "response_text" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateResponseText() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateResponseText()
	})
}

// ClearResponseText clears the value of the "response_text" field.
func (u *HoneypotEventUpsertBulk) ClearResponseText() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.ClearResponseText()
	})
}

// SetResponseMode sets the "response_mode" field.
func (u *HoneypotEventUpsertBulk) SetResponseMode(v string) *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.SetResponseMode(v)
	})
}

// UpdateResponseMode sets the "response_mode" field to the value that was provided on create.
func (u *HoneypotEventUpsertBulk) UpdateResponseMode() *HoneypotEventUpsertBulk {
	return u.Update(func(s *HoneypotEventUpsert) {
		s.UpdateResponseMode()
	})
}

// Exec executes the query.
func (u *HoneypotEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HoneypotEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HoneypotEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HoneypotEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
